# This file was generated by GoReleaser. DO NOT EDIT.
class Cider < Formula
  desc "Submit your builds to the Apple App Store in seconds"
  homepage "https://cidertool.github.io/cider"
  version "0.0.10"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/cidertool/cider/releases/download/v0.0.10/cider_darwin_x86_64.tar.gz"
    sha256 "0c8ffc32060d1744f20129f3dc8c4a3e80474f7a2a38e6bf4611679fd9949396"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/cidertool/cider/releases/download/v0.0.10/cider_linux_x86_64.tar.gz"
      sha256 "efc94c986e2b2ab4e99fd35e086abb8eb1467f396dd80252e14c53ae170c175b"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cidertool/cider/releases/download/v0.0.10/cider_linux_arm64.tar.gz"
        sha256 "299ff634daa36311700a485256f40274dbff1dc7c4e50ab876b99a78cc962911"
      else
      end
    end
  end

  def install
    bin.install "cider"
  end

  test do
    system "#{bin}/cider", "-v"
  end
end
