# This file was generated by GoReleaser. DO NOT EDIT.
class Cider < Formula
  desc "Submit your builds to the Apple App Store in seconds"
  homepage "https://cidertool.github.io/cider"
  version "0.0.8"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/cidertool/cider/releases/download/v0.0.8/cider_darwin_x86_64.tar.gz"
    sha256 "7b7fde98e47b876ef0a04bf91c425b7d3f224bf68d7cbd4ac2c2daed4e2649e2"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/cidertool/cider/releases/download/v0.0.8/cider_linux_x86_64.tar.gz"
      sha256 "ed8f613e511e3fc5dff71fc90ea98a345e2fbb4d7b0d5621e338b34d537e919f"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cidertool/cider/releases/download/v0.0.8/cider_linux_arm64.tar.gz"
        sha256 "b75da3826d317d33cacd1a50266d85b7584d932efbeb9e0e2aaacf253a18f99e"
      else
      end
    end
  end

  def install
    bin.install "cider"
  end

  test do
    system "#{bin}/cider", "-v"
  end
end
